DROP TABLE Member;
CREATE TABLE Member(
  id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR NOT NULl,
  role VARCHAR(100) NOT NULL
);
SELECT * FROM Member;




DROP TABLE Chat;
CREATE TABLE Chat(
  id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INT REFERENCES Member(id) ON DELETE SET NULL,
  name VARCHAR(100) NOT NUll,
  created_at TIMESTAMP
);
SELECT * FROM Chat;


INSERT INTO Chat (owner_id, name, created_at) VALUES (1, 'What is homework today', TIMESTAMP '2004-10-19 10:23:54') ;
INSERT INTO Chat (owner_id, name, created_at) VALUES (1, 'Test', TIMESTAMP '2010-10-19 10:23:54') ;



DROP TABLE Message;
CREATE TABLE Message(
  id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT REFERENCES Member(id) ON DELETE SET NULL,
  chat_id INT REFERENCES Chat(id) ON DELETE SET NULL,
  text VARCHAR NOT NULL,
  sent_at TIMESTAMP
);

INSERT INTO Message (user_id, chat_id, text, sent_at) VALUES (1,1,'Hello Chat!', TIMESTAMP '2022-9-10 16:23:54');


DROP TABLE chat_member;
CREATE TABLE chat_member(
    member_id INT REFERENCES Member(id) ON DELETE SET NULL,
    chat_id INT REFERENCES Chat(id) ON DELETE SET NULL,
    primary key (member_id, chat_id)
);
SELECT * FROM chat_member;

INSERT INTO chat_member (member_id, chat_id) VALUES (2, 1);