DROP TABLE Member;
CREATE TABLE Member(
  id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR NOT NULl,
  role VARCHAR(100) NOT NULL
);
SELECT * FROM Member;




DROP TABLE Chat;
CREATE TABLE Chat(
  id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INT REFERENCES Member(id) ON DELETE SET NULL,
  name VARCHAR(100) NOT NUll,
  created_at TIMESTAMP
);
SELECT * FROM Chat;


INSERT INTO Chat (owner_id, name, created_at) VALUES (1, 'What is homework today', TIMESTAMP '2004-10-19 10:23:54') ;
INSERT INTO Chat (owner_id, name, created_at) VALUES (1, 'Test', TIMESTAMP '2010-10-19 10:23:54') ;




DROP TABLE Message;
CREATE TABLE Message(
  id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT REFERENCES Member(id) ON DELETE SET NULL,
  chat_id INT REFERENCES Chat(id) ON DELETE SET NULL,
  text VARCHAR NOT NULL,
  sent_at TIMESTAMP
);

INSERT INTO Message (user_id, chat_id, text, sent_at) VALUES (1,1,'Hello Chat!', TIMESTAMP '2022-9-10 16:23:54');

SELECT * FROM Message;

DROP TABLE chat_member;
CREATE TABLE chat_member(
    member_id INT REFERENCES Member(id) ON DELETE SET NULL,
    chat_id INT REFERENCES Chat(id) ON DELETE SET NULL,
    primary key (member_id)
);
SELECT * FROM chat_member;


INSERT INTO chat_member (member_id, chat_id) VALUES (2, 1);

DELETE  from chat_member where member_id=1;


DROP TABLE chat_messages;
CREATE TABLE chat_messages(
    chat_id INT REFERENCES Chat(id) ON DELETE SET NULL,
    message_id INT REFERENCES Message(id) ON DELETE SET NULL,
    primary key (message_id)
);

SELECT * FROM chat_messages;
-- select messages0_.chat_id as chat_id1_2_0_, messages0_.messages_id as messages2_2_0_, message1_.id as id1_4_1_, message1_.chat_id as chat_id2_4_1_,
--        message1_.sent_at as sent_at3_4_1_, message1_.text as text4_4_1_, message1_.user_id as user_id5_4_1_
-- from chat_messages messages0_ inner join message message1_ on messages0_.messages_id=message1_.id where messages0_.chat_id=?;
--
-- select messages0_.chat_id as chat_id2_2_0_, messages0_.messages_id as messages6_2_0_, message1_.id as id1_2_1_,
--        message1_.chat_id as chat_id2_2_1_, message1_.sent_at as sent_at3_2_1_, message1_.text as text4_2_1_,
--        message1_.user_id as user_id5_2_1_ from chat_messages messages0_ inner join chat_messages message1_ on messages0_.messages_id=message1_.id where messages0_.chat_id=?